require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'
