require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
