AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~
