# Build Options
language: ruby
rvm: 2.6.6
node_js: "10.15.3"
env:
  - NODE_OPTIONS="--max_old_space_size=4096"
install:
  - bundle install
  - nvm install 10.15.3
  - node -v
  - npm i -g yarn
  - yarn install
before_script:
  - bin/webpack
  - cp .rspec.example .rspec
  - cp .rubocop.example .rubocop
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - bundle exec rake assets:precompile webpacker:compile
  - AUTHENTICATION_SESSION_KEY="$(bundle exec rails secret)" bundle exec rails server --port=5101 --daemon
script:
  - bundle exec thor ci:steps
after_script:
  - kill -9 $(cat tmp/pids/server.pid)

# Travis-CI Configuration
sudo: false # Enable containerized builds.
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
addons:
  chrome: stable
  postgresql: 9.6
